<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8dba756d-33dd-4021-97a1-ff897da5a1c0</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_d_ng_c_n_u_n</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="item\ \ item--category\ "]:nth-child(2)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Dụng cụ nấu ăn')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Dụng cụ nấu ăn</value>
        <webElementGuid>d6d95c58-1d07-4bc2-bcc1-092efd2926ea</webElementGuid>
    </webElementProperties>
</WebElementEntity>