<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>aacca296-aca1-4ff2-8b20-2c4f5193891c</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_art_photography</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="item\ \ item--category\ "]:nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Art &amp; Photography')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Art &amp; Photography</value>
        <webElementGuid>d6d95c58-1d07-4bc2-bcc1-092efd2926ea</webElementGuid>
    </webElementProperties>
</WebElementEntity>