<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>885640e4-2a49-49e5-9f02-bf6845e4d961</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_i_n_gia_d_ng</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/header[1]/div[1]/div[1]/div[2]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="style__StyledHeaderKeyWordsRevamp-sc-1tmiyrh-1\ eiBeGc"] &gt; a:nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'điện gia dụng')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>điện gia dụng</value>
        <webElementGuid>d6d95c58-1d07-4bc2-bcc1-092efd2926ea</webElementGuid>
    </webElementProperties>
</WebElementEntity>