<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>febe8ce2-98fa-4ec4-99a8-88727cd8c423</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_thi_t_b_s_ph_ki_n_s</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[6]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="styles__StyledListItem-sc-w7gnxl-0\ cjqkgR"]:nth-child(1) &gt; [class="styles__StyledItemV2-sc-oho8ay-1\ bHIPhv"]:nth-child(6) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Thiết Bị Số - Phụ Kiện Số')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Thiết Bị Số - Phụ Kiện Số</value>
        <webElementGuid>b66030f6-5f6f-435c-a68a-b590a244b5fb</webElementGuid>
    </webElementProperties>
</WebElementEntity>