<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a07bc257-048a-4834-8d40-b83a9334612b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_nh_s_ch_tiki</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="styles__StyledListItem-sc-w7gnxl-0\ cjqkgR"]:nth-child(1) &gt; [class="styles__StyledItem-sc-oho8ay-0\ bzmzGe"]:nth-child(2)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Nhà Sách Tiki')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Nhà Sách Tiki</value>
        <webElementGuid>d6d95c58-1d07-4bc2-bcc1-092efd2926ea</webElementGuid>
    </webElementProperties>
</WebElementEntity>