<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f9433e69-356f-4165-b528-e3d146b25695</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_nh_s_ch_tiki</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="styles__StyledListItem-sc-w7gnxl-0\ cjqkgR"]:nth-child(1) &gt; [class="styles__StyledItemV2-sc-oho8ay-1\ bHIPhv"]:nth-child(2) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Nhà Sách Tiki')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Nhà Sách Tiki</value>
        <webElementGuid>f48ba7b8-3fa1-4991-a674-5a24e86a3a6c</webElementGuid>
    </webElementProperties>
</WebElementEntity>