<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>15ae7d3e-4d29-463a-b99a-5b2efd230894</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_nh_c_a_i_s_ng</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="styles__StyledListItem-sc-w7gnxl-0\ cjqkgR"]:nth-child(1) &gt; [class="styles__StyledItemV2-sc-oho8ay-1\ bHIPhv"]:nth-child(3) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Nhà Cửa - Đời Sống')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Nhà Cửa - Đời Sống</value>
        <webElementGuid>b66030f6-5f6f-435c-a68a-b590a244b5fb</webElementGuid>
    </webElementProperties>
</WebElementEntity>