<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8f12d7cc-c334-4741-88b5-825c190bba5b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_ch_i_m_b</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[5]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="styles__StyledListItem-sc-w7gnxl-0\ cjqkgR"]:nth-child(1) &gt; [class="styles__StyledItemV2-sc-oho8ay-1\ bHIPhv"]:nth-child(5) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Đồ Chơi - Mẹ &amp; Bé')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Đồ Chơi - Mẹ &amp; Bé</value>
        <webElementGuid>b66030f6-5f6f-435c-a68a-b590a244b5fb</webElementGuid>
    </webElementProperties>
</WebElementEntity>