<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>30672ac7-4684-41df-85b3-98402b47ffdd</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_kh_e_p</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/header[1]/div[1]/div[1]/div[2]/div[2]/div[1]/a[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="style__StyledHeaderKeyWordsRevamp-sc-1tmiyrh-1\ eiBeGc"] &gt; a:nth-child(4)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'khỏe đẹp')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>khỏe đẹp</value>
        <webElementGuid>b66030f6-5f6f-435c-a68a-b590a244b5fb</webElementGuid>
    </webElementProperties>
</WebElementEntity>