<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0f7a0bf9-234a-403b-b5ff-7cf672b99e8d</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_kh_e_p</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/header[1]/div[1]/div[1]/div[2]/div[2]/div[1]/a[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="style__StyledHeaderKeyWordsRevamp-sc-1tmiyrh-1\ eiBeGc"] &gt; a:nth-child(4)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'khỏe đẹp')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>khỏe đẹp</value>
        <webElementGuid>f48ba7b8-3fa1-4991-a674-5a24e86a3a6c</webElementGuid>
    </webElementProperties>
</WebElementEntity>