<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>de189c75-4ad0-413c-ba7d-d441be4a1648</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_nh_c_a</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/header[1]/div[1]/div[1]/div[2]/div[2]/div[1]/a[5]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="style__StyledHeaderKeyWordsRevamp-sc-1tmiyrh-1\ eiBeGc"] &gt; a:nth-child(5)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'nhà cửa')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>nhà cửa</value>
        <webElementGuid>d6d95c58-1d07-4bc2-bcc1-092efd2926ea</webElementGuid>
    </webElementProperties>
</WebElementEntity>