<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9d81c898-03a9-4433-8f29-3e39ef559cfb</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_i_n_gia_d_ng</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/header[1]/div[1]/div[1]/div[2]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="style__StyledHeaderKeyWordsRevamp-sc-1tmiyrh-1\ eiBeGc"] &gt; a:nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'điện gia dụng')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>điện gia dụng</value>
        <webElementGuid>b66030f6-5f6f-435c-a68a-b590a244b5fb</webElementGuid>
    </webElementProperties>
</WebElementEntity>